os: linux
language: java
dist: trusty
sudo: false
jdk: oraclejdk8

env:
   global:
      - DISPLAY=:99.0  
   before_install:
      - sh -e /etc/init.d/xvfb start - sleep 10  

script: mvn clean verify
  
cache:
  directories:
    - '~/.m2/repository'

notifications:
  email: false
