os: linux
language: java
dist: xenial
jdk: oraclejdk8
services:
  - xvfb
sudo: false

env:
   global:
      - DISPLAY=:99.0  
   before_install:
      - sh -e /etc/init.d/xvfb start - sleep 10  

script: mvn clean verify
  
cache:
  directories:
    - '~/.m2/repository'

notifications:
  email: false
